### PR TITLE
Feature one: the full youtube  clone 

### PR DESCRIPTION
**Pull request by gabrie-lhilarion**
## In the branch we

* Added the video player
* Added the thumbnails to the right side of the page
* Created the comment area

### CODE REVIEW

**Comment by majovanilla** [comment]
Hey team, 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯

- Good Readme file
- Good Pull Request Message
- Your project meets all the requirements successfully except for these:

### Required Changes: ✍️

- Always remember to activate your repo in Stickler. I cannot see your linters working!!

- Improve your Readme file. It should be descriptive of the project. Here's a great [template](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) I strongly recommend you to use.

- Improve your HTML file, You have a lot of extra space in some parts and that is not necessary and makes your code difficult to read. 

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Your project would look so much better if you include the hover effects on the links of the page, like the original version.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by gabrie-lhilarion** [comment]
rrindrajosia@gmail.com

**Comment by uryelah** [comment]
Hello **Josia Rakotonarivo**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all great job with your first Microverse project! 🌟**

There are still two small requirements you are missing, but considering the effort you put in the project, it will be a piece of cake to fix them! 💪

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] Make sure there are no errors or warnings on the HTML validator. [Use this one.](https://validator.w3.org/nu)

- [ ] The 'share' element under the video should be a button tag, optionally the other clickable elements under the video would also be semantically better as `<button>`s.

- [ ] [OPTIONAL] Add a `cursor: pointer` property to your button and clickable elements so it's more user friendly.

-----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by sumancrest0001** [comment]
**Congratulation TEAM. Your project is approved.** :clap: :clap: 
It ticked all the requirements from the curriculum. You can merge the branch to the master. Do not forget to fill up the project completion form.
**Happy coding**
mission

**Pull request merged**
